[functions]

  [functions._ipx]
  node_bundler = "nft"

  [functions.___netlify-handler]
  included_files = [
    ".env",
    ".env.local",
    ".env.production",
    ".env.production.local",
    "./public/locales/**",
    "./next-i18next.config.js",
    ".next/server/**",
    ".next/serverless/**",
    ".next/*.json",
    ".next/BUILD_ID",
    ".next/static/chunks/webpack-middleware*.js",
    "!.next/server/**/*.js.nft.json",
    "!.next/server/**/*.map",
    "!**/node_modules/@next/swc*/**/*",
    "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
    "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
    "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
    "!node_modules/next/dist/compiled/webpack/bundle4.js",
    "!node_modules/next/dist/compiled/webpack/bundle5.js",
    "node_modules/styled-jsx/style.js"
  ]
  external_node_modules = []
  node_bundler = "nft"

  [functions.___netlify-odb-handler]
  included_files = [
    ".env",
    ".env.local",
    ".env.production",
    ".env.production.local",
    "./public/locales/**",
    "./next-i18next.config.js",
    ".next/server/**",
    ".next/serverless/**",
    ".next/*.json",
    ".next/BUILD_ID",
    ".next/static/chunks/webpack-middleware*.js",
    "!.next/server/**/*.js.nft.json",
    "!.next/server/**/*.map",
    "!**/node_modules/@next/swc*/**/*",
    "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
    "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
    "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
    "!node_modules/next/dist/compiled/webpack/bundle4.js",
    "!node_modules/next/dist/compiled/webpack/bundle5.js",
    "node_modules/styled-jsx/style.js"
  ]
  external_node_modules = []
  node_bundler = "nft"

  [functions."_api_*"]
  included_files = [
    ".env",
    ".env.local",
    ".env.production",
    ".env.production.local",
    "./public/locales/**",
    "./next-i18next.config.js",
    ".next/server/**",
    ".next/serverless/**",
    ".next/*.json",
    ".next/BUILD_ID",
    ".next/static/chunks/webpack-middleware*.js",
    "!.next/server/**/*.js.nft.json",
    "!.next/server/**/*.map",
    "!**/node_modules/@next/swc*/**/*",
    "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
    "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
    "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
    "!node_modules/next/dist/compiled/webpack/bundle4.js",
    "!node_modules/next/dist/compiled/webpack/bundle5.js",
    "node_modules/styled-jsx/style.js"
  ]
  external_node_modules = []
  node_bundler = "nft"

[build]

  [build.environment]
  NEXT_PRIVATE_TARGET = "server"

[[headers]]
for = "/*"

  [headers.values]
  Access-Control-Allow-Origin = "*"

[[redirects]]
from = "/_next/static/*"
to = "/static/:splat"
status = 200

[[redirects]]
from = "/_next/image*"
to = "/_ipx/w_:width,q_:quality/:url"
status = 301

  [redirects.query]
  url = ":url"
  w = ":width"
  q = ":quality"

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/builders/_ipx"
status = 200

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/_headers"
to = "/_headers"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/assets/AboutSection.mp4"
to = "/assets/AboutSection.mp4"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/assets/HowItWorks1.png"
to = "/assets/HowItWorks1.png"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/assets/HowItWorks2.png"
to = "/assets/HowItWorks2.png"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/assets/HowItWorks3.png"
to = "/assets/HowItWorks3.png"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/assets/SingleCard.png"
to = "/assets/SingleCard.png"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/assets/black_logo.png"
to = "/assets/black_logo.png"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/assets/grid2.png"
to = "/assets/grid2.png"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/assets/grid8.png"
to = "/assets/grid8.png"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/assets/hero.png"
to = "/assets/hero.png"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/assets/hero_img.png"
to = "/assets/hero_img.png"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/assets/logo.png"
to = "/assets/logo.png"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/assets/temp_logo.png"
to = "/assets/temp_logo.png"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/*"
to = "/.netlify/functions/___netlify-handler"
status = 200
force = true

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/_next/data/fvSF62LeFsjB4xMsWmjPJ/index.json"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/_next/data/fvSF62LeFsjB4xMsWmjPJ/about.json"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/about"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/_next/data/fvSF62LeFsjB4xMsWmjPJ/howitworks.json"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/howitworks"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/_next/data/fvSF62LeFsjB4xMsWmjPJ/login.json"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/login"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/_next/data/fvSF62LeFsjB4xMsWmjPJ/register.json"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/register"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/_next/data/fvSF62LeFsjB4xMsWmjPJ/shop.json"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/shop"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/_next/data/fvSF62LeFsjB4xMsWmjPJ/profile/:id.json"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/profile/:id"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/*"
to = "/.netlify/functions/___netlify-handler"
status = 200

[context]

  [context.production]

    [context.production.environment]
    NEXT_PRIVATE_TARGET = "server"

    [context.production.functions]

      [context.production.functions._ipx]
      node_bundler = "nft"

      [context.production.functions.___netlify-handler]
      included_files = [
        ".env",
        ".env.local",
        ".env.production",
        ".env.production.local",
        "./public/locales/**",
        "./next-i18next.config.js",
        ".next/server/**",
        ".next/serverless/**",
        ".next/*.json",
        ".next/BUILD_ID",
        ".next/static/chunks/webpack-middleware*.js",
        "!.next/server/**/*.js.nft.json",
        "!.next/server/**/*.map",
        "!**/node_modules/@next/swc*/**/*",
        "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
        "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/compiled/webpack/bundle4.js",
        "!node_modules/next/dist/compiled/webpack/bundle5.js",
        "node_modules/styled-jsx/style.js"
      ]
      external_node_modules = []
      node_bundler = "nft"

      [context.production.functions.___netlify-odb-handler]
      included_files = [
        ".env",
        ".env.local",
        ".env.production",
        ".env.production.local",
        "./public/locales/**",
        "./next-i18next.config.js",
        ".next/server/**",
        ".next/serverless/**",
        ".next/*.json",
        ".next/BUILD_ID",
        ".next/static/chunks/webpack-middleware*.js",
        "!.next/server/**/*.js.nft.json",
        "!.next/server/**/*.map",
        "!**/node_modules/@next/swc*/**/*",
        "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
        "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/compiled/webpack/bundle4.js",
        "!node_modules/next/dist/compiled/webpack/bundle5.js",
        "node_modules/styled-jsx/style.js"
      ]
      external_node_modules = []
      node_bundler = "nft"

      [context.production.functions."_api_*"]
      included_files = [
        ".env",
        ".env.local",
        ".env.production",
        ".env.production.local",
        "./public/locales/**",
        "./next-i18next.config.js",
        ".next/server/**",
        ".next/serverless/**",
        ".next/*.json",
        ".next/BUILD_ID",
        ".next/static/chunks/webpack-middleware*.js",
        "!.next/server/**/*.js.nft.json",
        "!.next/server/**/*.map",
        "!**/node_modules/@next/swc*/**/*",
        "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
        "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/compiled/webpack/bundle4.js",
        "!node_modules/next/dist/compiled/webpack/bundle5.js",
        "node_modules/styled-jsx/style.js"
      ]
      external_node_modules = []
      node_bundler = "nft"

    [context.production.build]

      [context.production.build.environment]
      NEXT_PRIVATE_TARGET = "server"

  [context.main]

    [context.main.environment]
    NEXT_PRIVATE_TARGET = "server"

    [context.main.functions]

      [context.main.functions._ipx]
      node_bundler = "nft"

      [context.main.functions.___netlify-handler]
      included_files = [
        ".env",
        ".env.local",
        ".env.production",
        ".env.production.local",
        "./public/locales/**",
        "./next-i18next.config.js",
        ".next/server/**",
        ".next/serverless/**",
        ".next/*.json",
        ".next/BUILD_ID",
        ".next/static/chunks/webpack-middleware*.js",
        "!.next/server/**/*.js.nft.json",
        "!.next/server/**/*.map",
        "!**/node_modules/@next/swc*/**/*",
        "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
        "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/compiled/webpack/bundle4.js",
        "!node_modules/next/dist/compiled/webpack/bundle5.js",
        "node_modules/styled-jsx/style.js"
      ]
      external_node_modules = []
      node_bundler = "nft"

      [context.main.functions.___netlify-odb-handler]
      included_files = [
        ".env",
        ".env.local",
        ".env.production",
        ".env.production.local",
        "./public/locales/**",
        "./next-i18next.config.js",
        ".next/server/**",
        ".next/serverless/**",
        ".next/*.json",
        ".next/BUILD_ID",
        ".next/static/chunks/webpack-middleware*.js",
        "!.next/server/**/*.js.nft.json",
        "!.next/server/**/*.map",
        "!**/node_modules/@next/swc*/**/*",
        "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
        "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/compiled/webpack/bundle4.js",
        "!node_modules/next/dist/compiled/webpack/bundle5.js",
        "node_modules/styled-jsx/style.js"
      ]
      external_node_modules = []
      node_bundler = "nft"

      [context.main.functions."_api_*"]
      included_files = [
        ".env",
        ".env.local",
        ".env.production",
        ".env.production.local",
        "./public/locales/**",
        "./next-i18next.config.js",
        ".next/server/**",
        ".next/serverless/**",
        ".next/*.json",
        ".next/BUILD_ID",
        ".next/static/chunks/webpack-middleware*.js",
        "!.next/server/**/*.js.nft.json",
        "!.next/server/**/*.map",
        "!**/node_modules/@next/swc*/**/*",
        "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
        "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/compiled/webpack/bundle4.js",
        "!node_modules/next/dist/compiled/webpack/bundle5.js",
        "node_modules/styled-jsx/style.js"
      ]
      external_node_modules = []
      node_bundler = "nft"

    [context.main.build]

      [context.main.build.environment]
      NEXT_PRIVATE_TARGET = "server"